samples:
    SRR9875279: data/SRR9875279_S1_L001_R1_001.fastq.gz
    SRR9875280: data/SRR9875280_S1_L001_R1_001.fastq.gz
    SRR9875281: data/SRR9875281_S1_L001_R1_001.fastq.gz
    SRR9875282: data/SRR9875282_S1_L001_R1_001.fastq.gz
    SRR9875283: data/SRR9875283_S1_L001_R1_001.fastq.gz
    SRR9875284: data/SRR9875284_S1_L001_R1_001.fastq.gz
    SRR9875285: data/SRR9875285_S1_L001_R1_001.fastq.gz
    SRR9875286: data/SRR9875286_S1_L001_R1_001.fastq.gz
    SRR9875287: data/SRR9875287_S1_L001_R1_001.fastq.gz
    SRR9875288: data/SRR9875288_S1_L001_R1_001.fastq.gz
    SRR9875289: data/SRR9875289_S1_L001_R1_001.fastq.gz
    SRR9875290: data/SRR9875290_S1_L001_R1_001.fastq.gz
    SRR9875291: data/SRR9875291_S1_L001_R1_001.fastq.gz

# cellranger options
cr_path: "~/local/cellranger-6.1.1/bin/cellranger"
ref: "ref/GRCh38"
chemistry: "SC3Pv2"
